project_id = "ckoocdzeiclocwiscmic"

[functions.invite-analyst]
verify_jwt = false

[functions.ingest-threatfox]
verify_jwt = false

[functions.ingest-sans-isc]
verify_jwt = false

[functions.ingest-ransomwatch]
verify_jwt = false

[functions.ingest-tor-exits]
verify_jwt = false

[functions.ingest-mastodon]
verify_jwt = false

[functions.check-pwned-password]
verify_jwt = false

[functions.ingest-coordinator]
verify_jwt = false

[functions.ingest-cisa-kev]
verify_jwt = false

[functions.ingest-otx-pulses]
verify_jwt = false

[functions.ingest-threats]
verify_jwt = false
