project_id = "ckoocdzeiclocwiscmic"

[functions.invite-analyst]
verify_jwt = false

[functions.ingest-threatfox]
verify_jwt = false

[functions.ingest-sans-isc]
verify_jwt = false

[functions.ingest-ransomwatch]
verify_jwt = false

[functions.ingest-tor-exits]
verify_jwt = false

[functions.ingest-mastodon]
verify_jwt = false

[functions.check-pwned-password]
verify_jwt = false

[functions.ingest-coordinator]
verify_jwt = false

[functions.ingest-cisa-kev]
verify_jwt = false

[functions.ingest-otx-pulses]
verify_jwt = false

[functions.ingest-threats]
verify_jwt = false

[functions.revoke-sessions]
verify_jwt = false

[functions.ingest-feodo]
verify_jwt = false

[functions.ingest-malbazaar]
verify_jwt = false

[functions.ingest-blocklist-de]
verify_jwt = false

[functions.ingest-ssl-blocklist]
verify_jwt = false

[functions.ingest-spamhaus-drop]
verify_jwt = false

[functions.ingest-certstream]
verify_jwt = false

[functions.ingest-google-safebrowsing]
verify_jwt = false

[functions.ingest-greynoise]
verify_jwt = false

[functions.ingest-phishtank-community]
verify_jwt = false

[functions.ingest-abuseipdb]
verify_jwt = false

[functions.ingest-virustotal]
verify_jwt = false

[functions.ingest-ipqualityscore]
verify_jwt = false
